name: SiteContagem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/testes-sitecontagem
  ASPNETCORE_URLS: 'http://localhost:5000'
  DIR_WEBAPP: './SiteContagem'
  LOG_EXECUTION_WEB: 'execution-webapp.log'
  DIR_TESTS: './Tests'
  TEST_SCRIPTS: './Tests/tests-sitecontagem.js'
  
jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.100
    - name: Executar a aplicação a ser testada em background (nohup)
      run: |
        dotnet publish ${{ env.DIR_WEBAPP }} -c Release -o app
        cd ./app
        nohup dotnet SiteContagem.dll > ${{ env.LOG_EXECUTION_WEB }} 2>&1 &
        echo 'Aguardando a inicialização da aplicação a ser testada...'
        sleep 10s
    - name: Instalar o k6
      run: |
        curl https://github.com/grafana/k6/releases/download/v0.35.0/k6-v0.35.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
        npm install
        ./k6
    - name: Executar testes de carga com k6
      run: |
        ./k6 run ${{ env.TEST_SCRIPTS }}
    - name: Exibir log de execução da aplicação após testes
      if: always()
      run: |
        cd ./app
        cat ${{ env.LOG_EXECUTION_WEB }}

  build:
    needs: [tests]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build de imagem
      run: |
        cd ${{ env.DIR_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest
    - name: Login no Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker tag ${{ env.IMAGEM_DOCKERHUB }}:latest ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER
        docker push --all-tags ${{ env.IMAGEM_DOCKERHUB }}